Small Refactoring: jefail refactored to C++
codereport/jsource pull request #17
Opened 2021-01-23 22:01 UTC by ahmadbeirkdar

jefail refactored to C++, throws invalid arugment exception
Sending this PR mainly to see if throwing exceptions is fine, instead of writing to stderr then exiting. And the style of refactoring. 

```
96% tests passed, 15 tests failed out of 406

Total Test time (real) = 269.18 sec

The following tests FAILED:
	118 - g210a (SEGFAULT)
	123 - g221 (Failed)
	137 - g300 (Failed)
	157 - g331 (SEGFAULT)
	183 - g420stch (SEGFAULT)
	226 - g5x30 (Failed)
	234 - g602 (Failed)
	257 - g9x40 (Failed)
	272 - gebar (Failed)
	303 - gmmf (Failed)
	304 - gmmf1s (Failed)
	305 - gmmf1u (Failed)
	306 - gmmf1w (Failed)
	397 - gu (Failed)
	398 - gu0 (Failed)
Errors while running CTest
```

2021-01-23 22:08 UTC, ahmadbeirkdar commented
Seems like linux is failing due to an old clang version being used to compiler, clang 7.0.0

2021-01-25 00:39 UTC, codereport requested changes
LGTM, just comment removal

2021-01-25 00:39 UTC, codereport commented on jsrc/jeload.cpp
> +//	char* input=static_cast<char* >(malloc(2000+strlen(arg)));
```suggestion
```

2021-01-25 00:39 UTC, codereport commented on jsrc/jeload.cpp
> +// Refactored to C++
```suggestion
```

2021-01-25 00:42 UTC, ahmadbeirkdar commented
> LGTM, just comment removal

Done!

2021-01-25 03:36 UTC, ahmadbeirkdar commented
Getting used to the CLion git client, seems like it messed up on my end, and I pushed the wrong commits.... My bad

2021-01-25 22:05 UTC, codereport approved these changes
:fire:

2021-01-25 22:05 UTC, merged