Convert isempty to C++
codereport/jsource pull request #208
Opened 2021-03-10 20:50 UTC by herwinw

A branch I had around. It's pretty much a direct copy from the C function, with a few remarks:
* I'm not sure what the return type of the call for a sparse array is. It calls `jteps`, which confuses me a lot. I'm not even sure why it does this.
* I thought about rewriting `AN` to something more descriptive, similar to the `is_sparse` function. However, this macro is used for assignment as well (see `make_array`), so I just left the C macro here. I think the consistency here is more important.

2021-03-11 07:32 UTC, juntuu commented
About the first point: `jteps(jt, needle, haystack)` implements `x e. y` which is "member in".
So in english, for sparse array `jtisempty` checks if zero is in the shape of the array (as the comment also says in j).

Generally the functions often have commented the corresponding j phrase, if not `t.c` is good place to check for primitives. Here for example `jtrazein` is the monadic case, and `jteps` is dyadic case of `e.`. https://github.com/codereport/jsource/blob/de91efce021f9e184113527d01a1e3bb373b3079/jsrc/t.c#L816 (and [j nuvoc](https://code.jsoftware.com/wiki/Vocabulary/edot#dyadic) to see what the primitive does)

2021-03-16 19:21 UTC, herwinw commented
That makes more sense than the `epsilon` how I read it

2021-03-16 22:54 UTC, codereport requested changes
Looks good! :pray: just a file rename / function rename and then we will :ship: it

2021-03-16 22:54 UTC, codereport commented on jsrc/CMakeLists.txt
> +        verbs/monadic/isempty.cpp
```suggestion
        verbs/monadic/is_empty.cpp
```

2021-03-16 22:54 UTC, codereport commented on jsrc/verbs/monadic/isempty.cpp
> +jtisempty(J jt, array w) -> array {
```suggestion
is_empty(J jt, array w) -> array {
```

2021-03-16 22:54 UTC, juntuu commented on jsrc/verbs/monadic/isempty.cpp
> + * @param w        Input aray
Just a typo
```suggestion
 * @param w        Input array
```

2024-10-12 18:19 UTC, closed without merging