Jeload.cpp refactoring
codereport/jsource pull request #25
Opened 2021-01-25 19:35 UTC by ahmadbeirkdar

Refactored jeload.cpp.
What's left is void* pointers which need to be done when other files are being refactored.

Added helper functions for strings, in util/

2021-01-25 23:14 UTC, codereport commented
Are you able to try and clean up the history (maybe `git rebase`)?

2021-01-25 23:21 UTC, ahmadbeirkdar commented
> Are you able to try and clean up the history (maybe `git rebase`)?

All done, my bad

2021-01-26 06:12 UTC, ahmadbeirkdar commented on util/stringx.h
> +#define J_STRINGX_H
For sure, it’s not a library, I wrote it as a “utility” function which came in handy and should be reusable around the code base

2021-01-26 06:18 UTC, ahmadbeirkdar commented on util/stringx.h
> +#define J_STRINGX_H
Named it stringx to not conflict with std::string, and to store all helper string functions

2021-01-26 16:01 UTC, codereport requested changes

2021-01-26 16:01 UTC, codereport commented on jsrc/util/stringx.h
> +    auto remove_all_occurrences(std::string &str, std::string_view const &sub_str) -> void;
`std::string_view` doesn't need to be `const&` because it is non-owning :slightly_smiling_face:

2021-01-27 01:35 UTC, codereport requested changes
We can merge after this.

2021-01-27 01:35 UTC, codereport commented on jsrc/CMakeLists.txt
> +        util/stringx.h
indentation

2021-01-27 01:35 UTC, codereport commented on jsrc/jeload.cpp
> +#include "util/stringx.h"
split standard and user headers

2021-01-27 01:35 UTC, codereport commented on jsrc/jeload.h
> +int jedo(const char*); // could be jedi
east const

2021-01-27 01:35 UTC, codereport commented on jsrc/util/stringx.cpp
> +
EOF newline

2021-01-27 01:35 UTC, codereport commented on jsrc/jeload.cpp
> +#include "util/stringx.h"
Also, i think it is fine to rename to `string.hpp/cpp`

2021-01-27 01:50 UTC, codereport approved these changes
lgtm :+1:

2021-01-27 01:50 UTC, merged